export const s = {
  root: { display: "flex", minHeight: "100vh", background: "#0D0D0F", color: "#F0EDE8", fontFamily: "'DM Sans',sans-serif" },
  sidebar: { width: 236, background: "#111114", borderRight: "1px solid #1E1E24", display: "flex", flexDirection: "column", padding: "26px 14px", position: "fixed", top: 0, bottom: 0, left: 0, zIndex: 100 },
  logo: { display: "flex", alignItems: "center", gap: 10, padding: "0 8px 26px" },
  logoTxt: { fontFamily: "'Syne',sans-serif", fontSize: 23, fontWeight: 800, letterSpacing: "-0.5px" },
  nav: { display: "flex", flexDirection: "column", gap: 2, flex: 1 },
  navItem: { display: "flex", alignItems: "center", gap: 11, padding: "9px 12px", borderRadius: 9, border: "none", background: "transparent", color: "#888", cursor: "pointer", fontSize: 15, fontWeight: 500, transition: "all 0.2s", textAlign: "left" },
  navOn: { background: "#1E1E24", color: "#F0EDE8" },
  streakCard: { background: "linear-gradient(135deg,#FF6B35,#FF8C60)", borderRadius: 13, padding: "13px 15px", display: "flex", alignItems: "center", gap: 11 },
  streakN: { fontWeight: 800, fontSize: 16, color: "#fff", fontFamily: "'Syne',sans-serif" },
  streakL: { fontSize: 10, color: "rgba(255,255,255,0.8)" },
  main: { flex: 1, minHeight: "100vh" },
  topBar: { position: "sticky", top: 0, zIndex: 9, background: "rgba(13,13,15,0.88)", backdropFilter: "blur(16px)", borderBottom: "1px solid #1E1E24", padding: "12px 24px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  topGreet: { fontFamily: "'Syne',sans-serif", fontSize: 15, fontWeight: 700, color: "#666" },
  iconCircle: { width: 36, height: 36, borderRadius: "50%", background: "#1A1A1F", border: "1px solid #2A2A30", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#999", position: "relative", transition: "all 0.2s" },
  iconOn: { background: "#252528", color: "#F0EDE8", borderColor: "#3A3A40" },
  badge: { position: "absolute", top: -4, right: -4, background: "#FF6B35", color: "#fff", borderRadius: "50%", width: 16, height: 16, fontSize: 10, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center", border: "2px solid #0D0D0F" },
  avatarBtn: { width: 36, height: 36, borderRadius: "50%", background: "linear-gradient(135deg,#FF6B35,#FF8C60)", border: "2px solid #2A2A30", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", overflow: "hidden", transition: "all 0.2s" },
  avatarOn: { borderColor: "#FF6B35", boxShadow: "0 0 0 3px rgba(255,107,53,0.2)" },
  initials: { fontFamily: "'Syne',sans-serif", fontSize: 11, fontWeight: 800, color: "#fff" },
  veil: { position: "fixed", inset: 0, zIndex: 8 },
  dropdown: { position: "absolute", top: "calc(100% + 9px)", right: 0, background: "#161618", border: "1px solid #2A2A30", borderRadius: 14, overflow: "hidden", zIndex: 50, boxShadow: "0 20px 60px rgba(0,0,0,0.6)" },
  ddHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "13px 16px", borderBottom: "1px solid #1E1E24" },
  ddTitle: { fontFamily: "'Syne',sans-serif", fontWeight: 700, fontSize: 13 },
  nRow: { display: "flex", alignItems: "flex-start", gap: 10, padding: "11px 16px", borderBottom: "1px solid #111116", cursor: "pointer" },
  nRowU: { background: "#1A1A1F" },
  toast: { position: "fixed", top: 22, right: 22, background: "#1A2A1A", border: "1px solid #2A4A2A", color: "#6EE7B7", borderRadius: 11, padding: "11px 18px", display: "flex", alignItems: "center", gap: 9, fontSize: 15, fontWeight: 600, zIndex: 200 },
  toastErr: { background: "#2A1A1A", border: "1px solid #4A2A2A", color: "#FCA5A5" },
  page: { padding: "20px 16px 56px", maxWidth: 940, margin: "0 auto", transition: "padding 0.3s" },
  pageHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24, flexWrap: "wrap", gap: 16 },
  pageTitle: { fontFamily: "'Syne',sans-serif", fontSize: 28, fontWeight: 800, margin: 0, letterSpacing: "-1px" },
  pageSub: { color: "#666", margin: "2px 0 0", fontSize: 13 },
  hero: { borderRadius: 20, overflow: "hidden", position: "relative", height: 300, marginBottom: 26 },
  heroBtn: { display: "inline-flex", alignItems: "center", gap: 8, background: "#FF6B35", border: "none", color: "#fff", borderRadius: 11, padding: "10px 18px", fontSize: 14, fontWeight: 700, cursor: "pointer", width: "fit-content", fontFamily: "'DM Sans',sans-serif" },
  statsRow: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(130px, 1fr))", gap: 12, marginBottom: 20 },
  statCard: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 14, padding: 16 },
  statV: { fontFamily: "'Syne',sans-serif", fontSize: 24, fontWeight: 800, lineHeight: 1 },
  statL: { fontSize: 11, color: "#666", marginTop: 4 },
  secTitle: { fontFamily: "'Syne',sans-serif", fontSize: 18, fontWeight: 700, margin: 0 },
  weekGrid: { display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: 4 },
  dayCell: { background: "#0D0D0F", border: "1px solid #1E1E24", borderRadius: 8, padding: "10px 4px", display: "flex", flexDirection: "column", alignItems: "center", gap: 5, transition: "all 0.2s" },
  dayCellDone: { background: "#FF6B351A", borderColor: "#FF6B35" },
  dayCellToday: { borderColor: "#FF6B35", borderWidth: 2 },
  recentCard: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 14, padding: "14px 18px", display: "flex", alignItems: "center", cursor: "pointer", marginTop: 10 },
  card: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 16, padding: 20 },
  cardTitle: { fontFamily: "'Syne',sans-serif", fontSize: 17, fontWeight: 800, margin: 0 },
  plansGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(250px,1fr))", gap: 14 },
  planCard: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 16, padding: 18, position: "relative", borderTop: "3px solid" },
  dayChip: { width: 26, height: 26, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 6, background: "#1A1A1F", fontSize: 10, fontWeight: 700 },
  newPlanCard: { background: "#111114", border: "2px dashed #222", borderRadius: 16, padding: "30px 18px", display: "flex", flexDirection: "column", alignItems: "center", gap: 8, cursor: "pointer" },
  cardIconBtn: { background: "transparent", border: "none", color: "#555", cursor: "pointer", padding: 5, borderRadius: 6, display: "flex", transition: "all 0.15s" },
  stepBar: { display: "flex", alignItems: "center", marginBottom: 26 },
  stepDot: { width: 32, height: 32, borderRadius: "50%", background: "#1A1A1F", border: "2px solid #2A2A30", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, color: "#555", flexShrink: 0, transition: "all 0.3s" },
  stepOn: { background: "#FF6B35", border: "2px solid #FF6B35", color: "#fff" },
  logCard: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 18, padding: 22 },
  logTitle: { fontFamily: "'Syne',sans-serif", fontSize: 21, fontWeight: 700, margin: "0 0 20px" },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 13, marginBottom: 13 },
  fg: { marginBottom: 13 },
  lbl: { display: "block", fontSize: 12, fontWeight: 600, color: "#888", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.5px" },
  inp: { width: "100%", background: "#0D0D0F", border: "1px solid #2A2A30", borderRadius: 9, padding: "9px 12px", color: "#F0EDE8", fontSize: 14, fontFamily: "'DM Sans',sans-serif", outline: "none", boxSizing: "border-box" },
  addBtn: { background: "#FF6B35", border: "none", borderRadius: 9, padding: "0 12px", color: "#fff", cursor: "pointer", display: "flex", alignItems: "center" },
  exBlock: { background: "#0D0D0F", borderRadius: 11, padding: 13, marginBottom: 9 },
  setsH: { display: "grid", gridTemplateColumns: "32px 1fr 1fr", gap: 7, fontSize: 10, color: "#555", fontWeight: 700, textTransform: "uppercase", marginBottom: 6 },
  setRow: { display: "grid", gridTemplateColumns: "32px 1fr 1fr", gap: 7, marginBottom: 5, alignItems: "center" },
  setN: { width: 22, height: 22, borderRadius: "50%", background: "#1A1A1F", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, color: "#666", fontWeight: 700 },
  setInp: { background: "#1A1A1F", border: "1px solid #2A2A30", borderRadius: 6, padding: "5px 6px", color: "#F0EDE8", fontSize: 12, fontFamily: "'DM Sans',sans-serif", outline: "none", textAlign: "center" },
  addSetBtn: { background: "transparent", border: "1px dashed #2A2A30", color: "#666", borderRadius: 6, padding: "4px 10px", cursor: "pointer", fontSize: 11, marginTop: 5, fontFamily: "'DM Sans',sans-serif" },
  photoBox: { border: "2px dashed #2A2A30", borderRadius: 11, overflow: "hidden", cursor: "pointer" },
  primaryBtn: { background: "#FF6B35", border: "none", borderRadius: 10, padding: "10px 18px", color: "#fff", fontSize: 14, fontWeight: 700, cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 7, fontFamily: "'DM Sans',sans-serif", transition: "all 0.2s" },
  secBtn: { background: "#1A1A1F", border: "1px solid #2A2A30", borderRadius: 10, padding: "10px 18px", color: "#aaa", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans',sans-serif", transition: "all 0.2s" },
  histCard: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 13, padding: "14px 18px", display: "flex", alignItems: "center", gap: 12, cursor: "pointer" },
  wDetail: { background: "#111114", border: "1px solid #1E1E24", borderRadius: 18, padding: 22 },
  backBtn: { background: "transparent", border: "none", color: "#888", cursor: "pointer", fontSize: 14, padding: "0 0 16px", display: "flex", alignItems: "center", gap: 5, fontFamily: "'DM Sans',sans-serif" },
  overlay2: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.85)", backdropFilter: "blur(12px)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 110, padding: 16 },
  modal: { background: "#111114", border: "1px solid #2A2A30", borderRadius: 18, padding: 22, width: "100%", maxWidth: 430, maxHeight: "90vh", overflowY: "auto" },
  modalTitle: { fontFamily: "'Syne',sans-serif", fontSize: 20, fontWeight: 800, margin: "0 0 16px" },
  toggle: { width: 38, height: 20, borderRadius: 10, background: "#2A2A30", cursor: "pointer", position: "relative", transition: "background 0.3s" },
  toggleOn: { background: "#FF6B35" },
  thumb: { position: "absolute", top: 3, left: 3, width: 14, height: 14, borderRadius: "50%", background: "#fff", transition: "transform 0.3s" },
  thumbOn: { transform: "translateX(18px)" },
  iconBtnS: { background: "transparent", border: "none", color: "#444", cursor: "pointer", display: "flex", padding: 3 },
  dayToggle: { background: "#1A1A1F", border: "1px solid #2A2A30", borderRadius: 6, padding: "5px 10px", color: "#aaa", cursor: "pointer", fontSize: 12, fontFamily: "'DM Sans',sans-serif", fontWeight: 600, transition: "all 0.2s" },
};
